import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os
from flask import Flask, redirect, request, session, jsonify
from dotenv import load_dotenv
from services.spotify import build_taste_profile
from services.lastfm import search_by_tag, build_candidate_pool
from services.llm import extract_search_params, rank_and_explain
from services.lastfm import build_candidate_pool

load_dotenv()

app = Flask(__name__, static_folder='static', static_url_path='')
app.secret_key = os.getenv('SECRET_KEY')

# Spotify scopes — permissions asking from user
SCOPE = 'user-top-read user-library-read playlist-modify-public playlist-modify-private'

def get_redirect_uri():
    if os.getenv('RENDER'):
        return f"https://{os.getenv('RENDER_EXTERNAL_HOSTNAME')}/callback"
    return 'http://localhost:5000/callback'

def get_spotify_oauth():
    return SpotifyOAuth(
        client_id=os.getenv('SPOTIFY_CLIENT_ID'),
        client_secret=os.getenv('SPOTIFY_CLIENT_SECRET'),
        redirect_uri=get_redirect_uri(),
        scope=SCOPE
    )

def get_spotify_client():
    token_info = session.get('token_info')
    if not token_info:
        return None
    # Auto-refresh token if expired
    sp_oauth = get_spotify_oauth()
    if sp_oauth.is_token_expired(token_info):
        token_info = sp_oauth.refresh_access_token(token_info['refresh_token'])
        session['token_info'] = token_info
    return spotipy.Spotify(auth=token_info['access_token'])

@app.route('/')
def home():
    return app.send_static_file('index.html')

@app.route('/login')
def login():
    sp_oauth = get_spotify_oauth()
    auth_url = sp_oauth.get_authorize_url()
    return redirect(auth_url)

@app.route('/logout')
def logout():
    session.clear()
    return redirect('/')

@app.route('/callback')
def callback():
    sp_oauth = get_spotify_oauth()
    code = request.args.get('code')
    token_info = sp_oauth.get_access_token(code)
    session['token_info'] = token_info
    return redirect('/')

@app.route('/me')
def me():
    sp = get_spotify_client()
    if not sp:
        return jsonify({'error': 'not logged in'}), 401
    user = sp.current_user()
    top_tracks = sp.current_user_top_tracks(limit=15, time_range='medium_term')
    return jsonify({
        'name': user['display_name'],
        'top_tracks': [t['name'] + ' — ' + t['artists'][0]['name'] 
                       for t in top_tracks['items']]
    })

@app.route('/taste-profile')
def taste_profile():
    sp = get_spotify_client()
    if not sp:
        return jsonify({'error': 'not logged in'}), 401
    profile = build_taste_profile(sp)
    session['taste_profile'] = profile  # store it for later use
    return jsonify(profile)

@app.route('/search', methods=['POST'])
def search():
    sp = get_spotify_client()
    if not sp:
        return jsonify({'error': 'not logged in'}), 401

    # data = request.get_json()
    # user_query = data.get('query', '')
    user_query = "songs that feel like a nightclub" # hardcoded for now to speed up testing, replace with above in prod

    if not user_query:
        return jsonify({'error': 'no query provided'}), 400

    # Get taste profile (from session if already fetched, otherwise fetch now)
    taste_profile = session.get('taste_profile')
    if not taste_profile:
        taste_profile = build_taste_profile(sp)
        session['taste_profile'] = taste_profile

    # Step 1: LLM extracts search parameters from user's query
    search_params = extract_search_params(user_query)
    print('Search params:', search_params)  # helpful for debugging

    # Step 2: Last.fm builds candidate pool using those params
    candidates = build_candidate_pool(
        genres=search_params.get('genres', []),
        ref_artists=search_params.get('ref_artists', [])
    )
    print(f'Candidates found: {len(candidates)}')

    # Step 3: LLM ranks candidates against user taste + explains picks
    recommendations = rank_and_explain(user_query, taste_profile, candidates)

    return jsonify({
        'query': user_query,
        'search_params': search_params,  # useful to show user what the LLM understood
        'recommendations': recommendations
    })

@app.route('/save-playlist', methods=['POST'])
def save_playlist():
    sp = get_spotify_client()
    if not sp:
        return jsonify({'error': 'not logged in'}), 401

    data = request.get_json()
    query = data.get('query', 'Moodify playlist')
    songs = data.get('songs', [])

    # Create the playlist
    try:
        playlist = sp.current_user_playlist_create(
            name=f"Moodify: {query}",
            public=False,
            description=f"Generated by Moodify for: {query}"
        )
    except Exception as e:
        print(f'Error creating playlist: {e}')
        return jsonify({'error': f'Failed to create playlist: {str(e)}'}), 500

    # Search each song on Spotify to get its URI
    track_uris = []
    for song in songs:
        try:
            result = sp.search(
                q=f"track:{song['name']} artist:{song['artist']}",
                type='track',
                limit=1
            )
            tracks = result['tracks']['items']
            if tracks:
                track_uris.append(tracks[0]['uri'])
        except Exception as e:
            print(f'Error searching for song {song["name"]}: {e}')

    # Add tracks to playlist
    try:
        if track_uris:
            sp.playlist_add_items(playlist['id'], track_uris)
    except Exception as e:
        print(f'Error adding tracks to playlist: {e}')
        return jsonify({'error': f'Failed to add tracks: {str(e)}'}), 500

    return jsonify({
        'success': True,
        'playlist_url': playlist['external_urls']['spotify'],
        'tracks_added': len(track_uris)
    })

#debugging
@app.route('/debug-redirect')
def debug_redirect():
    return jsonify({
        'redirect_uri_being_used': get_redirect_uri(),
        'render_hostname': os.getenv('RENDER_EXTERNAL_HOSTNAME'),
        'is_render': os.getenv('RENDER')
    })
if __name__ == '__main__':
    if os.getenv('RENDER'):
        app.run(host='0.0.0.0', port=10000)
    else:
        app.run(debug=False)